// src/ai/tools/documentCatalog.js
//
// Product-specific document and artifact generation schemas.

import envConfig from '../../config/env.js';
import { makeTool } from './schema.js';

const TOOL_GENERATE_FORMAL_REQUEST_PDF = makeTool({
  name: 'generate_formal_request_pdf',
  description: 'Generate a PDF for a formal request and save it in your workspace. Never use emojis. Do NOT use markdown headings (# ## etc.) but you can use **bold**, *italic*, bullet lists. Date and filename are generated automatically. The footer "Generated by GemiX..." is added automatically by the system - do not include it.',
  properties: {
    fullName: { type: 'string', description: 'Full name of the requester' },
    title: { type: 'string', description: 'Request title' },
    motivation: { type: 'string', description: 'Detailed and well-argued motivation' },
    requesterSignature: { type: 'string', description: 'Requester signature' },
    legalSignature: { type: 'string', description: `Legal advisor signature ("${envConfig.LEGAL_NAME}" if requested by him in person, or "Nessuno")` }
  },
  required: ['fullName', 'title', 'motivation', 'requesterSignature']
});

export { TOOL_GENERATE_FORMAL_REQUEST_PDF };
