// src/ai/tools/documentCatalog.js
//
// Product-specific document and artifact generation schemas.

import { LEGAL_NAME } from '../../config/members.js';
import { makeTool } from './schema.js';

const _FORMAL_REQUEST_BASE_DESCRIPTION = 'Generate a PDF for a formal request and save it in your workspace. Never use emojis. Do NOT use markdown headings (# ## etc.) but you can use **bold**, *italic*, bullet lists. Date and filename are generated automatically. The footer "Generated by GemiX..." is added automatically by the system - do not include it.';

/**
 * Formal request PDF schema.
 *
 * The legal signature is the countersignature that makes a request valid, and
 * only the legal advisor can give it, from his own turn: for everyone else the
 * field is absent, so it cannot be filled in on his behalf.
 *
 * @param {boolean} isLegal - true when the caller is the legal advisor
 */
function buildGenerateFormalRequestPdfTool(isLegal) {
  const properties = {
    fullName: { type: 'string', description: 'Full name of the requester' },
    title: { type: 'string', description: 'Request title' },
    motivation: { type: 'string', description: 'Detailed and well-argued motivation' },
    requesterSignature: { type: 'string', description: 'Requester signature' }
  };

  if (isLegal) {
    properties.legalSignature = {
      type: 'string',
      description: `Legal advisor signature ("${LEGAL_NAME}" if he asks for it in this turn, or "Nessuno")`
    };
  }

  return makeTool({
    name: 'generate_formal_request_pdf',
    description: isLegal
      ? _FORMAL_REQUEST_BASE_DESCRIPTION
      : `${_FORMAL_REQUEST_BASE_DESCRIPTION} The request goes out unsigned by the legal advisor: only ${LEGAL_NAME} can countersign it, and only from his own turn, so the request becomes valid when he asks you to generate it himself.`,
    properties,
    required: ['fullName', 'title', 'motivation', 'requesterSignature']
  });
}

export { buildGenerateFormalRequestPdfTool };
