// src/ai/tools/preferenceCatalog.js
//
// Per-chat preferences and small product-level tools that do not belong to a
// provider or delivery backend.

import envConfig from '../../config/env.js';
import {
  activeEffortPolicy,
  defaultSettings,
  VALID_LANGUAGES,
  VALID_VOICES,
  VOICES_FEMALE,
  VOICES_MALE
} from '../../utils/settingsStore.js';
import { makeTool } from './schema.js';

function buildManagePreferencesTool(isGroup, isPersonalChat = false) {
  const scope = isGroup
    ? 'the current group'
    : (isPersonalChat ? 'this shared personal chat (both participants)' : 'the current user');
  const defaults = defaultSettings();
  const { supportedEfforts } = activeEffortPolicy();
  return makeTool({
    name: 'manage_preferences',
    description: `Change your own settings for ${scope} — the ones listed in CurrentSettings (voice, effort, language, custom memory). `
      + 'Pass only the fields to change; the others stay as they are. Values marked (default) there are the program defaults. '
      + 'Never store transient context (current task, session state, temporary data).',
    properties: {
      voice: {
        type: 'string',
        enum: VALID_VOICES,
        description: `Voice used for spoken replies (default ${defaults.voice}). `
          + `Male: ${VOICES_MALE.join(', ')}. Female: ${VOICES_FEMALE.join(', ')}. `
          + 'Pick the one matching the gender and character the user asks for.'
      },
      effort: {
        type: 'string',
        enum: supportedEfforts,
        description: `How much reasoning you spend per reply. Supported by the current main model: ${supportedEfforts.join(', ')}; `
          + `default ${defaults.effort}, the highest available. Lower is faster; higher is more thorough.`
      },
      language: {
        type: 'string',
        enum: VALID_LANGUAGES,
        description: `Language you reply and speak in (default ${defaults.language}). Main codes: it, en, es-ES, fr, de, pt-BR, zh, ja, ru, ar-SA.`
      },
      memory: {
        type: 'string',
        allowEmpty: true,
        description: 'Free-text custom instructions, for anything not covered by the fields above: '
          + 'e.g. speak with a certain slang, use lots of emoji, always prefer text or voice replies, or what the user is working on in this period '
          + '(ideas/projects that stay relevant for days, weeks or months — never a one-off question or transient context). '
          + 'Max 1000 chars, always in English; empty resets it to the default. Do not write timestamps: the system tracks them.'
      },
      replace: { type: 'boolean', description: 'Only affects `memory`: true (default) = rewrite it, false = append to the existing text.' }
    }
  });
}

const TOOL_TOGGLE_RELEASE_NOTIFY = makeTool({
  name: 'toggle_release_notify',
  description: 'Enable or disable new GemiX release notifications for this chat.',
  properties: { enabled: { type: 'boolean', description: 'true=enable, false=disable' } },
  required: ['enabled']
});

const TOOL_GENERATE_FORMAL_REQUEST_PDF = makeTool({
  name: 'generate_formal_request_pdf',
  description: 'Generate a PDF for a formal request and save it in your workspace. Never use emojis. Do NOT use markdown headings (# ## etc.) but you can use **bold**, *italic*, bullet lists. Date and filename are generated automatically. The footer "Generated by GemiX..." is added automatically by the system - do not include it.',
  properties: {
    fullName: { type: 'string', description: 'Full name of the requester' },
    title: { type: 'string', description: 'Request title' },
    motivation: { type: 'string', description: 'Detailed and well-argued motivation' },
    requesterSignature: { type: 'string', description: 'Requester signature' },
    legalSignature: { type: 'string', description: `Legal advisor signature ("${envConfig.LEGAL_NAME}" if requested by him in person, or "Nessuno")` }
  },
  required: ['fullName', 'title', 'motivation', 'requesterSignature']
});

const TOOL_GENERATE_MUSIC = makeTool({
  name: 'generate_music',
  description: 'Create a 30-second music clip from a prompt. The clip is saved in your workspace.',
  properties: { prompt: { type: 'string', description: 'Detailed description of style, instruments, and mood.' } },
  required: ['prompt']
});

const TOOL_BUG_REPORT = makeTool({
  name: 'bug_report',
  description: 'Report a bug/failure. Always use this when a tool errors and the error does NOT already state the admin was notified, or for general logical bugs / system-component issues (unclear instructions, unexpected behavior, bugs noted in chat history). After reporting, inform the user of the problem and that the admin has been notified in your final response.',
  properties: {
    description: { type: 'string', description: 'Brief but clear description of the problem (what failed, where, and any relevant context).' }
  },
  required: ['description']
});

export {
  TOOL_BUG_REPORT,
  TOOL_GENERATE_FORMAL_REQUEST_PDF,
  TOOL_GENERATE_MUSIC,
  TOOL_TOGGLE_RELEASE_NOTIFY,
  buildManagePreferencesTool
};
