// src/config/env.js
require('dotenv').config();

module.exports = {
  OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY,
  FAST_MODEL: process.env.FAST_MODEL,
  AGENTIC_MODEL: process.env.AGENTIC_MODEL,
  EMBEDDING_MODEL: process.env.EMBEDDING_MODEL,
  BROWSE_PAGE_MODEL: process.env.BROWSE_PAGE_MODEL,
  MEDIA_DESCRIBER_MODEL: process.env.MEDIA_DESCRIBER_MODEL,
  XAI_API_KEY: process.env.XAI_API_KEY,
  XAI_TTS_VOICE: process.env.XAI_TTS_VOICE,
  SEARXNG_URL: process.env.SEARXNG_URL,
  BOT_TOKEN: process.env.BOT_TOKEN,
  GUILD_ID: process.env.GUILD_ID,
  BOT_EMAIL: process.env.BOT_EMAIL,
  BOT_PASS: process.env.BOT_PASS,
  MUSIC_WRAP_PASSWORD: process.env.MUSIC_WRAP_PASSWORD,
  GITHUB_TOKEN: process.env.GITHUB_TOKEN,
  GITHUB_REPO: process.env.GITHUB_REPO,
  GEMIX_NOTIFY_URL: process.env.GEMIX_NOTIFY_URL,
  OPENDATALOADER_HYBRID_URL: process.env.OPENDATALOADER_HYBRID_URL,
  OPENDATALOADER_HYBRID_TIMEOUT: Number(process.env.OPENDATALOADER_HYBRID_TIMEOUT)
};
