// src/utils/attachments.js
// Unified attachment shape used across responseCtx.
// An attachment is: { name, mimetype, buffer?, filePath? }
//   - buffer:   Buffer already in memory (small/in-flight files: voice, image_search thumbs, formal PDF)
//   - filePath: absolute path on disk (preferred for files generated by bash / write_file
//               to avoid loading big payloads in RAM until delivery)
//
// Exactly one of buffer/filePath must be set. Helpers below encapsulate the
// "read-on-demand" logic so platform senders don't have to care.

const fs = require('fs');
const path = require('path');

/**
 * @typedef {{ name: string, mimetype: string, buffer?: Buffer, filePath?: string }} Attachment
 */

/**
 * Compute a buffer-unique filename. If `rawName`'s basename is already taken
 * by another attachment in `existing`, append "(1)", "(2)"… before the
 * extension until free. Returns the basename only (paths are never stored as
 * the logical name).
 *
 * @param {Attachment[]} existing
 * @param {string} rawName
 * @returns {string}
 */
function uniqueAttachmentName(existing, rawName) {
  const base = path.basename(String(rawName || 'file').trim()) || 'file';
  const taken = new Set(
    (Array.isArray(existing) ? existing : [])
      .map(a => (a && a.name ? path.basename(a.name) : null))
      .filter(Boolean),
  );
  if (!taken.has(base)) return base;
  const ext = path.extname(base);
  const stem = base.slice(0, base.length - ext.length);
  let i = 1;
  let candidate;
  do {
    candidate = `${stem}(${i})${ext}`;
    i++;
  } while (taken.has(candidate) && i < 100000);
  return candidate;
}

/**
 * Push an attachment into `responseCtx.attachments`, guaranteeing its logical
 * `name` is unique within the buffer (renaming to "name(1).ext" on clash).
 * Returns the FINAL name actually stored so the caller can report it to the
 * model in the same tool result — the model addresses files by name, so it
 * must learn the post-dedup name immediately (never "renamed afterwards",
 * which would otherwise pollute the conversation).
 *
 * Every name-addressed feature relies on buffer names being collision-free:
 *   - reference_images resolution in generate_image / generate_video,
 *   - attachments[] filename matching handed to the build sub-agent,
 *   - the model citing searched / generated images by name in later turns.
 *
 * Note: this dedups only against the in-memory buffer. The temp-disk and the
 * public tunnel are already collision-proof on their own (random file
 * prefixes + unique per-file tokens), so they need no coordination here.
 *
 * @param {object} responseCtx
 * @param {Attachment} att - { name, mimetype, buffer?|filePath? }
 * @returns {string} the final, buffer-unique name stored
 */
function pushBufferAttachment(responseCtx, att) {
  if (!responseCtx || typeof responseCtx !== 'object') {
    throw new Error('pushBufferAttachment: responseCtx is required');
  }
  if (!att || !att.name) {
    throw new Error('pushBufferAttachment: attachment with a name is required');
  }
  if (!Array.isArray(responseCtx.attachments)) responseCtx.attachments = [];
  const finalName = uniqueAttachmentName(responseCtx.attachments, att.name);
  responseCtx.attachments.push({ ...att, name: finalName });
  return finalName;
}

function isValidAttachment(att) {
  if (!att || typeof att !== 'object') return false;
  if (!att.name || !att.mimetype) return false;
  const hasBuffer = Buffer.isBuffer(att.buffer);
  const hasPath = typeof att.filePath === 'string' && att.filePath.length > 0;
  return hasBuffer || hasPath;
}

/**
 * Resolve an attachment to an in-memory Buffer.
 * Reads from disk if only filePath is set.
 * @param {Attachment} att
 * @returns {Buffer|null}
 */
function readAttachmentBuffer(att) {
  if (!isValidAttachment(att)) return null;
  if (Buffer.isBuffer(att.buffer)) return att.buffer;
  try {
    return fs.readFileSync(att.filePath);
  } catch {
    return null;
  }
}

/**
 * Return the size in bytes of an attachment without necessarily loading it.
 */
function attachmentSize(att) {
  if (!isValidAttachment(att)) return 0;
  if (Buffer.isBuffer(att.buffer)) return att.buffer.length;
  try { return fs.statSync(att.filePath).size; } catch { return 0; }
}

/**
 * Shape an attachment for nodemailer. Prefers streaming from disk when possible.
 */
function toEmailAttachment(att) {
  if (!isValidAttachment(att)) return null;
  const base = { filename: att.name, contentType: att.mimetype };
  if (typeof att.filePath === 'string') return { ...base, path: att.filePath };
  return { ...base, content: att.buffer };
}

/**
 * Shape an attachment for whatsapp-web.js MessageMedia.
 * Returns { mimetype, base64, name } that can be passed to `new MessageMedia(...)`.
 */
function toWhatsAppMediaArgs(att) {
  const size = attachmentSize(att);
  if (size > 100 * 1024 * 1024) {
    // Too large for direct WhatsApp sending — return null to trigger fallback
    return null;
  }
  const buf = readAttachmentBuffer(att);
  if (!buf) return null;
  return { mimetype: att.mimetype, base64: buf.toString('base64'), name: att.name };
}

/**
 * Shape an attachment for Discord AttachmentBuilder. Buffer path is fine;
 * for very large files on-disk we pass the filePath directly.
 * @returns {{ data: Buffer|string, name: string } | null}
 */
function toDiscordAttachmentArgs(att) {
  if (!isValidAttachment(att)) return null;
  if (typeof att.filePath === 'string') return { data: att.filePath, name: att.name };
  return { data: att.buffer, name: att.name };
}

module.exports = {
  isValidAttachment,
  uniqueAttachmentName,
  pushBufferAttachment,
  readAttachmentBuffer,
  attachmentSize,
  toEmailAttachment,
  toWhatsAppMediaArgs,
  toDiscordAttachmentArgs,
};
