// src/utils/attachments.js
// Unified attachment shape used across responseCtx.
// An attachment is: { name, mimetype, buffer?, filePath? }
//   - buffer:   Buffer already in memory (small/in-flight files: voice, image_search thumbs, formal PDF)
//   - filePath: absolute path on disk (preferred for files generated by code_execution / write_file
//               to avoid loading big payloads in RAM until delivery)
//
// Exactly one of buffer/filePath must be set. Helpers below encapsulate the
// "read-on-demand" logic so platform senders don't have to care.

const fs = require('fs');

/**
 * @typedef {{ name: string, mimetype: string, buffer?: Buffer, filePath?: string, _imageSearchId?: number }} Attachment
 */

function isValidAttachment(att) {
  if (!att || typeof att !== 'object') return false;
  if (!att.name || !att.mimetype) return false;
  const hasBuffer = Buffer.isBuffer(att.buffer);
  const hasPath = typeof att.filePath === 'string' && att.filePath.length > 0;
  return hasBuffer || hasPath;
}

/**
 * Resolve an attachment to an in-memory Buffer.
 * Reads from disk if only filePath is set.
 * @param {Attachment} att
 * @returns {Buffer|null}
 */
function readAttachmentBuffer(att) {
  if (!isValidAttachment(att)) return null;
  if (Buffer.isBuffer(att.buffer)) return att.buffer;
  try {
    return fs.readFileSync(att.filePath);
  } catch {
    return null;
  }
}

/**
 * Return the size in bytes of an attachment without necessarily loading it.
 */
function attachmentSize(att) {
  if (!isValidAttachment(att)) return 0;
  if (Buffer.isBuffer(att.buffer)) return att.buffer.length;
  try { return fs.statSync(att.filePath).size; } catch { return 0; }
}

/**
 * Shape an attachment for nodemailer. Prefers streaming from disk when possible.
 */
function toEmailAttachment(att) {
  if (!isValidAttachment(att)) return null;
  const base = { filename: att.name, contentType: att.mimetype };
  if (typeof att.filePath === 'string') return { ...base, path: att.filePath };
  return { ...base, content: att.buffer };
}

/**
 * Shape an attachment for whatsapp-web.js MessageMedia.
 * Returns { mimetype, base64, name } that can be passed to `new MessageMedia(...)`.
 */
function toWhatsAppMediaArgs(att) {
  const size = attachmentSize(att);
  if (size > 100 * 1024 * 1024) {
    // Too large for direct WhatsApp sending — return null to trigger fallback
    return null;
  }
  const buf = readAttachmentBuffer(att);
  if (!buf) return null;
  return { mimetype: att.mimetype, base64: buf.toString('base64'), name: att.name };
}

/**
 * Shape an attachment for Discord AttachmentBuilder. Buffer path is fine;
 * for very large files on-disk we pass the filePath directly.
 * @returns {{ data: Buffer|string, name: string } | null}
 */
function toDiscordAttachmentArgs(att) {
  if (!isValidAttachment(att)) return null;
  if (typeof att.filePath === 'string') return { data: att.filePath, name: att.name };
  return { data: att.buffer, name: att.name };
}

module.exports = {
  isValidAttachment,
  readAttachmentBuffer,
  attachmentSize,
  toEmailAttachment,
  toWhatsAppMediaArgs,
  toDiscordAttachmentArgs,
};
