// src/utils/attachments.js
// Unified attachment shape used across responseCtx.
// An attachment is: { name, mimetype, buffer?, filePath?, externalUrl?, waTempLinkPreferred? }
//   - buffer:   Buffer already in memory (small/in-flight files: voice, image_search thumbs, formal PDF)
//   - filePath: absolute path on disk (for files generated by bash / write_file
//               ; large payloads stay on disk until delivery)
//   - externalUrl: source link when the file cannot be hosted (e.g. URL >100 MB)
//   - waTempLinkPreferred: build-agent audio/video only (normal delivery uses size only)
//
// At least one of buffer, filePath, or externalUrl must be set. Helper functions handle
// read-on-demand from disk.

const fs = require('fs');
const path = require('path');
const { mimeBase } = require('../config/mimeExtensions');

/** WhatsApp direct send cap (whatsapp-web.js); above → temp download link. */
const WA_DIRECT_MAX_BYTES = 100 * 1024 * 1024;

const WA_TEMP_LINK_AUDIO_EXTS = new Set([
  '.mp3', '.mpeg', '.mpga', '.ogg', '.opus', '.oga', '.wav', '.m4a', '.flac', '.aac', '.webm',
]);
const WA_TEMP_LINK_VIDEO_EXTS = new Set([
  '.mp4', '.webm', '.mov', '.mkv', '.avi', '.m4v',
]);

/**
 * @typedef {{ name: string, mimetype: string, buffer?: Buffer, filePath?: string, externalUrl?: string, waTempLinkPreferred?: boolean, sendAudioAsVoice?: boolean }} Attachment
 */

/**
 * Compute a buffer-unique filename. If `rawName`'s basename is already taken
 * by another attachment in `existing`, append "(1)", "(2)..." before the
 * extension until free. Returns the basename only (paths are never stored as
 * the logical name).
 *
 * @param {Attachment[]} existing
 * @param {string} rawName
 * @returns {string}
 */
function uniqueAttachmentName(existing, rawName) {
  const base = path.basename(String(rawName || 'file').trim()) || 'file';
  const taken = new Set(
    (Array.isArray(existing) ? existing : [])
      .map(a => (a && a.name ? path.basename(a.name) : null))
      .filter(Boolean),
  );
  if (!taken.has(base)) return base;
  const ext = path.extname(base);
  const stem = base.slice(0, base.length - ext.length);
  let i = 1;
  let candidate;
  do {
    candidate = `${stem}(${i})${ext}`;
    i++;
  } while (taken.has(candidate) && i < 100000);
  return candidate;
}

/**
 * Push an attachment into `responseCtx.attachments`, guaranteeing its logical
 * `name` is unique within the buffer (renaming to "name(1).ext" on clash).
 * Returns the final unique name stored.
 *
 * @param {object} responseCtx
 * @param {Attachment} att - { name, mimetype, buffer?|filePath? }
 * @returns {string} the final, buffer-unique name stored
 */
function pushBufferAttachment(responseCtx, att) {
  if (!responseCtx || typeof responseCtx !== 'object') {
    throw new Error('pushBufferAttachment: responseCtx is required');
  }
  if (!att || !att.name) {
    throw new Error('pushBufferAttachment: attachment with a name is required');
  }
  if (!Array.isArray(responseCtx.attachments)) responseCtx.attachments = [];
  const finalName = uniqueAttachmentName(responseCtx.attachments, att.name);
  responseCtx.attachments.push({ ...att, name: finalName });
  return finalName;
}

function isValidAttachment(att) {
  if (!att || typeof att !== 'object') return false;
  if (!att.name || !att.mimetype) return false;
  const hasBuffer = Buffer.isBuffer(att.buffer);
  const hasPath = typeof att.filePath === 'string' && att.filePath.length > 0;
  const hasExternal = typeof att.externalUrl === 'string' && att.externalUrl.trim().length > 0;
  return hasBuffer || hasPath || hasExternal;
}

/**
 * Resolve an attachment to an in-memory Buffer.
 * Reads from disk if only filePath is set.
 * @param {Attachment} att
 * @returns {Buffer|null}
 */
function readAttachmentBuffer(att) {
  if (!isValidAttachment(att)) return null;
  if (hasExternalUrlOnly(att)) return null;
  if (Buffer.isBuffer(att.buffer)) return att.buffer;
  try {
    return fs.readFileSync(att.filePath);
  } catch {
    return null;
  }
}

/**
 * Return the size in bytes of an attachment without necessarily loading it.
 */
function attachmentSize(att) {
  if (!att || typeof att !== 'object') return 0;
  if (typeof att.externalUrl === 'string' && att.externalUrl.trim()) return 0;
  if (Buffer.isBuffer(att.buffer)) return att.buffer.length;
  if (typeof att.filePath === 'string' && att.filePath.length > 0) {
    try { return fs.statSync(att.filePath).size; } catch { return 0; }
  }
  return 0;
}

/**
 * Shape an attachment for nodemailer. Prefers streaming from disk when possible.
 */
function toEmailAttachment(att) {
  if (!isValidAttachment(att)) return null;
  const base = { filename: att.name, contentType: att.mimetype };
  if (typeof att.filePath === 'string') return { ...base, path: att.filePath };
  return { ...base, content: att.buffer };
}

/** True for audio/video payloads (not voice-note TTS). */
function isWhatsAppAudioVideoAttachment(att) {
  if (!att || att.sendAudioAsVoice) return false;
  const mt = mimeBase(att.mimetype || '');
  if (mt.startsWith('audio/') || mt.startsWith('video/')) return true;
  const ext = path.extname(att.name || '').toLowerCase();
  return WA_TEMP_LINK_AUDIO_EXTS.has(ext) || WA_TEMP_LINK_VIDEO_EXTS.has(ext);
}

function isWhatsAppOversizedAttachment(att) {
  return attachmentSize(att) > WA_DIRECT_MAX_BYTES;
}

/**
 * Prefer public temp download link before attempting direct WA media send.
 * - Oversized files (>100 MB) — all sources, all types
 * - waTempLinkPreferred: build-agent audio/video only
 * Failed direct sends still fall back to temp links.
 */
function shouldWhatsAppUseTempLink(att) {
  if (att?.sendAudioAsVoice) return false;
  return isWhatsAppOversizedAttachment(att) || Boolean(att.waTempLinkPreferred);
}

/**
 * Shape an attachment for whatsapp-web.js MessageMedia.
 * Returns { mimetype, base64, name } that can be passed to `new MessageMedia(...)`.
 */
function toWhatsAppMediaArgs(att) {
  if (shouldWhatsAppUseTempLink(att)) {
    return null;
  }
  const buf = readAttachmentBuffer(att);
  if (!buf) return null;
  return { mimetype: att.mimetype, base64: buf.toString('base64'), name: att.name };
}

/**
 * Shape an attachment for Discord AttachmentBuilder. The filePath is used
 * for very large files on disk.
 * @returns {{ data: Buffer|string, name: string } | null}
 */
function toDiscordAttachmentArgs(att) {
  if (hasExternalUrlOnly(att)) return null;
  if (!isValidAttachment(att)) return null;
  if (typeof att.filePath === 'string') return { data: att.filePath, name: att.name };
  return { data: att.buffer, name: att.name };
}

function hasExternalUrlOnly(att) {
  return typeof att?.externalUrl === 'string' && att.externalUrl.trim().length > 0;
}

module.exports = {
  isValidAttachment,
  uniqueAttachmentName,
  pushBufferAttachment,
  readAttachmentBuffer,
  attachmentSize,
  shouldWhatsAppUseTempLink,
  WA_DIRECT_MAX_BYTES,
  toEmailAttachment,
  toWhatsAppMediaArgs,
  toDiscordAttachmentArgs,
};
