// Video type detection for generated bytes. A media URL or Content-Type can
// lie; staging uses the container signature so the extension matches the file.

/**
 * @param {Buffer} buffer
 * @returns {{ ext: string, mime: string }|null} extension has no leading dot
 */
function sniffVideoType(buffer) {
  if (!Buffer.isBuffer(buffer) || buffer.length < 12) return null;

  // ISO Base Media File Format: MP4/M4V and QuickTime all carry `ftyp` at 4.
  if (buffer.subarray(4, 8).toString('ascii') === 'ftyp') {
    const brand = buffer.subarray(8, 12).toString('ascii');
    return brand === 'qt  '
      ? { ext: 'mov', mime: 'video/quicktime' }
      : { ext: 'mp4', mime: 'video/mp4' };
  }

  // WebM is an EBML container whose document begins with this magic number.
  if (buffer[0] === 0x1A && buffer[1] === 0x45 && buffer[2] === 0xDF && buffer[3] === 0xA3) {
    return { ext: 'webm', mime: 'video/webm' };
  }
  return null;
}

export { sniffVideoType };
